Suppose the given preference score of nurse \( i \) for shift \( j \) is $ c_{ij} $, where $ i \in \{1, 2, \ldots, 7\} $ and $ j \in \{1, 2, \ldots, 21\} $.

Let our decision variable be $ x_{ij} $, where $ x_{ij} = 1 $ if nurse \( i \) is assigned shift \( j \), and 0 otherwise.

We have to:
$$
\max \sum_{i=1}^{7} \sum_{j=1}^{21} c_{ij} \cdot x_{ij}
$$

Subject to the following constraints:
$$
\sum_{i=1}^{7} x_{ij} = 1 \quad \forall j \in \{1, 2, \ldots, 21\},
$$

$$
\sum_{j=1}^{21} x_{ij} \leq 5 \quad \forall i \in \{1, 2, \ldots, 7\},
$$

$$
\sum_{j=3k-2}^{3k} x_{ij} \leq 1 \quad \forall i, k \in \{1, 2, \ldots, 7\},
$$

$$
x_{ij} + x_{i(j+1)} \leq 1 \quad \forall i \in \{1, 2, \ldots, 7\} \quad and \quad \forall j \in \{1, 2, \ldots, 20\},
$$

$$
x_{ij} \in \{0,1\} \quad \forall i \in \{1, 2, \ldots, 7\} \quad and \quad \forall j \in \{1, 2, \ldots, 21\}.
$$

In [38]:
import numpy as np
c = np.random.randint(0, 11, size=(7, 21))
print(c)

[[10  9  5  4  6  6 10  6  3  2  7  1  9  9  6 10  8  2  2  2 10]
 [ 4 10  9  9 10  6 10  6 10 10  4  3  8  1  4  9  4 10  4  7  6]
 [ 0  5  0  3  8 10  6  8  8  8  7 10  1  4  1  7  2  4  8  5  9]
 [ 5  8  1  8  1  6  1  2  3  3  1 10  9  5 10  0  6  6  6  4  8]
 [ 6  9  8  9  0  5  8  3  3  7  8  5  4  1  8  8  2  3  3  8  0]
 [ 3 10  9  1  1  4  0  3  1  9  9  8 10  8  2  2  9  2  9 10  4]
 [ 4  9  4 10  4  5  8  1  9  7  2  2  0  1  1  7 10 10  6  9  7]]


In [26]:
from gurobipy import Model, GRB

In [27]:
prob_1 = Model("Problem 1")

In [28]:
x = prob_1.addVars(c.shape[0], c.shape[1], vtype = GRB.BINARY, name = "x")

In [29]:
prob_1.addConstrs((sum(x[i,j] for i in range(c.shape[0])) == 1
                  for j in range(c.shape[1])))

prob_1.addConstrs((sum(x[i,j] for j in range(c.shape[1])) <= 5
                  for i in range(c.shape[0])))

prob_1.addConstrs((sum(x[i,j] for i in range(c.shape[0])) == 1
                  for j in range(c.shape[1])))


{0: <gurobi.Constr *Awaiting Model Update*>,
 1: <gurobi.Constr *Awaiting Model Update*>,
 2: <gurobi.Constr *Awaiting Model Update*>,
 3: <gurobi.Constr *Awaiting Model Update*>,
 4: <gurobi.Constr *Awaiting Model Update*>,
 5: <gurobi.Constr *Awaiting Model Update*>,
 6: <gurobi.Constr *Awaiting Model Update*>,
 7: <gurobi.Constr *Awaiting Model Update*>,
 8: <gurobi.Constr *Awaiting Model Update*>,
 9: <gurobi.Constr *Awaiting Model Update*>,
 10: <gurobi.Constr *Awaiting Model Update*>,
 11: <gurobi.Constr *Awaiting Model Update*>,
 12: <gurobi.Constr *Awaiting Model Update*>,
 13: <gurobi.Constr *Awaiting Model Update*>,
 14: <gurobi.Constr *Awaiting Model Update*>,
 15: <gurobi.Constr *Awaiting Model Update*>,
 16: <gurobi.Constr *Awaiting Model Update*>,
 17: <gurobi.Constr *Awaiting Model Update*>,
 18: <gurobi.Constr *Awaiting Model Update*>,
 19: <gurobi.Constr *Awaiting Model Update*>,
 20: <gurobi.Constr *Awaiting Model Update*>}

In [30]:
for i in range(c.shape[0]):
    for k in range(c.shape[0]):
        start_j = 3 * k   
        end_j = 3 * k + 2  
        if end_j < 21:
            prob_1.addConstr(sum(x[i, j] for j in range(start_j, end_j + 1)) <= 1)

In [31]:
for i in range(c.shape[0]):
    for j in range(20):  
        prob_1.addConstr(x[i, j] + x[i, j + 1] <= 1)

In [32]:
obj_fn = sum(c[i,j]*x[i,j] for i in range(c.shape[0]) for j in range(c.shape[1]))

prob_1.setObjective(obj_fn, GRB.MAXIMIZE)

In [36]:
prob_1.setParam("OutputFlag", False)
prob_1.optimize()

In [39]:

print("Objective Function Value: %f" % prob_1.objVal)

for v in prob_1.getVars():
    if v.x > 0:
       print("%s : %g" % (v.varName, v.x))

Objective Function Value: 183.000000
x[0,15] : 1
x[1,6] : 1
x[1,9] : 1
x[1,14] : 1
x[1,17] : 1
x[2,5] : 1
x[2,7] : 1
x[2,11] : 1
x[2,18] : 1
x[3,0] : 1
x[3,20] : 1
x[4,4] : 1
x[4,12] : 1
x[4,19] : 1
x[5,2] : 1
x[5,10] : 1
x[5,13] : 1
x[6,1] : 1
x[6,3] : 1
x[6,8] : 1
x[6,16] : 1
